### ISSUE TITLE
Does not handle iodata input

### ISSUE THREAD

**Issue by dantswain** [danschultzer/premailex#40]
I'm not 100% convinced that this is something your library should handle, but I thought I'd open a ticket for discussion.  `Premailex.to_inline_css/2` breaks if you supply iodata to it.  The reason this comes up is because Phoenix templates make use of iodata in constructing their output.

Handling this is as simple as calling `IO.iodata_to_binary/1` on the input:

```
def to_inline_css(html, options \\ [])
def to_inline_css(html, options) when is_binary(html) do
    Premailex.HTMLInlineStyles.process(html, options)
end
def to_inline_css(html, options), do: to_inline_css(IO.iodata_to_binary(html), options)
```

I think you could make a reasonable argument, though, that this conversion shouldn't be the concern of your library.  If that's the case, then just adding the `when is_binary(html)` guard could help clearly define your API.

**Comment by danschultzer** [comment]
Yeah, I have thought of this previously. The reason why I don't just run `IO.iodata_to_binary/1` is to not give off an idea that Premailex can do the operations on iodata for efficiency. It's just one more line of code when processing from iodata, and both Bamboo and Swoosh already generates a binary rather than iodata from the templates.

There is already `@spec` that should be picked up by dializer if you attempt to pass in iodata, so not sure if the guard is necessary? The docs already shows the accepted arguments: https://hexdocs.pm/premailex/Premailex.html#to_inline_css/2

**Comment by dantswain** [comment]
I agree the implementation doesn’t belong here. 

The spec helps dialyzer recognize the contract, but the guard makes it very strict. It will fail tests immediately and do so in a way that points directly at the problem. This could be a style thing. Just a suggestion. Feel free to close this.

**Comment by danschultzer** [comment]
Thought about this, and I think you're right. I've added guards in #45, thanks!
