### ISSUE TITLE
Premailer and @font-face

### ISSUE THREAD

**Issue by bitboxer** [danschultzer/premailex#48]
I just tried to add a `@font-face` definition to make the emails look a bit nicer for clients that support that. That made premailer spit out lots of warnings: `Unknown token '@'. Ignoring`. Will happily ignore them for now, just wanted to make sure you know this. And if you need any help fixing this, I would love to help you out on that one.

**Comment by danschultzer** [comment]
This happens because Floki attempts to up elements that matches `@font-face`. They should just be ignored by the [CSS parser](https://github.com/danschultzer/premailex/blob/v0.3.8/lib/premailex/css_parser.ex). This is done by stripping the rules before parsing them:

https://github.com/danschultzer/premailex/blob/64345557d01b22af381a599b9ece6b30aec3f3d8/lib/premailex/css_parser.ex#L120-L124

 You are more than welcome to create a PR!

**Comment by bitboxer** [comment]
Thanks for the hint where I have to fix it. PR will be coming in the next couple of days.
